// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWgHTAx4N5L7BC1tE4ENnW7NvQbgghcFs',
    appId: '1:403449078580:web:c6cd2857c6c03973e4bb61',
    messagingSenderId: '403449078580',
    projectId: 'kkfyp-3593a',
    authDomain: 'kkfyp-3593a.firebaseapp.com',
    storageBucket: 'kkfyp-3593a.firebasestorage.app',
    measurementId: 'G-2SKDLKGWBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQAK5spYliNzelebWnuSfM3Wvy-2yh8oc',
    appId: '1:403449078580:android:d0a8c1c7f1000a34e4bb61',
    messagingSenderId: '403449078580',
    projectId: 'kkfyp-3593a',
    storageBucket: 'kkfyp-3593a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWgHTAx4N5L7BC1tE4ENnW7NvQbgghcFs',
    appId: '1:403449078580:web:faf5f3b962c4cd97e4bb61',
    messagingSenderId: '403449078580',
    projectId: 'kkfyp-3593a',
    authDomain: 'kkfyp-3593a.firebaseapp.com',
    storageBucket: 'kkfyp-3593a.firebasestorage.app',
    measurementId: 'G-68M4NTPTPB',
  );
}
